- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 0 # Box: 0 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 0 # Box: 0 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 0 # Box: 0 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 28800 # Box: 8 hours
    # Box Change Start
    - !type:RoleTimeRequirement
      role: JobHeadOfPersonnel
      time: 7200 # 2 hrs
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 7200 # 2 hrs
    - !type:RoleTimeRequirement
      role: JobChiefEngineer
      time: 7200 # 2 hrs
    - !type:RoleTimeRequirement
      role: JobChiefMedicalOfficer
      time: 7200 # 2 hrs
    - !type:RoleTimeRequirement
      role: JobQuartermaster
      time: 7200 # 2 hrs
    - !type:RoleTimeRequirement
      role: JobResearchDirector
      time: 7200 # 2 hrs
    - !type:OverallPlaytimeRequirement
      time: 54000 # 15 hrs
    # Box Change End
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCommand
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter

- type: chameleonOutfit
  id: CaptainChameleonOutfit
  job: Captain
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
