- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - Bagel
  # - Box
  # - Fland
  # - Marathon
  # - Oasis
  # - Packed
  # - Plasma
  # - Reach
  # - Exo
  # - Snowball
# Box Change Start - Hardfork Maps
  - Amber
  - Aspid
  # - Atlas
  - Barratry
  - Elkridge
  - Jellyfish
  - Mira
  - Omega
  - Packed
  - Prime
  - Dove
# Box Change End
