- type: latheRecipe
  id: NapkinDrum
  result: NapkinDrum
  completetime: 1
  materials:
    Steel: 75

- type: latheRecipe
  id: Napkin
  result: Napkin
  completetime: 0.1
  materials:
    Wood: 10
