- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 0 # Harmony: 2.5h -> 0
    # Box Change Start
    - !type:DepartmentTimeRequirement
      department: Security
      time: 2h
    # Box Change End
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    # ears: ClothingHeadsetSecurity # Box Change: Headset moved to loadout option
  inhand:
    # Start Box Change - Replace generic briefcase with lawyer's own personal briefcase
    # - BriefcaseBrownFilled
    - BriefcaseLawyer
    # End Box Change
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw

- type: chameleonOutfit
  id: LawyerChameleonOutfit
  job: Lawyer
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
