- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 5h # 2.5h -> 0 # Box Change - 0h > 5h
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ScientistGear
# Start Box Change - Null startingGear for Scientist - Wrist Comms
#  equipment:
    # ears: ClothingHeadsetScience
  #storage:
    #back:
    #- Stuff
# End Box Change

- type: chameleonOutfit
  id: ScientistChameleonOutfit
  job: Scientist
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatRnd
    gloves: ClothingHandsGlovesLatex
