using Content.Shared._RMC14.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.UserInterface.Options;

[GenerateTypedNameReferences]
public sealed partial class VoicelinesTab : Control
{
    public VoicelinesTab()
    {
        RobustXamlLoader.Load(this);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesYourself, RMCVoicelinesYourself);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesYourself, RMCEmotesYourself);

        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesArachnid, RMCVoicelinesArachnid);
        //Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesDiona, RMCVoicelinesDiona); // Box Change: Dionae use human voice sounds
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesDwarf, RMCVoicelinesDwarf);
        // Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesFelinid, RMCVoicelinesFelinid); // Harmony - We don't have this
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesHuman, RMCVoicelinesHuman);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesMoth, RMCVoicelinesMoth);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesReptilian, RMCVoicelinesReptilian);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesSlime, RMCVoicelinesSlime);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesAvali, RMCVoicelinesAvali);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesVulpkanin, RMCVoicelinesVulpkanin);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesRodentia, RMCVoicelinesRodentia);
        // Harmony change start - We don't have these species but we do have Vox
        // Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesFeroxi, RMCVoicelinesFeroxi);
        // Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesSkrell, RMCVoicelinesSkrell);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesVox, RMCVoicelinesVox);
        // Harmony Change end
        // Start Box Change: Scurret, IPC, Allulalo 
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesScurret, RMCVoicelinesScurret);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesIPC, RMCVoicelinesIPC);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesAllulalo, RMCVoicelinesAllulalo);
        // End Box Change

        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesArachnid, RMCEmotesArachnid);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesDiona, RMCEmotesDiona);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesDwarf, RMCEmotesDwarf);
        // Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesFelinid, RMCEmotesFelinid); // Harmony - We don't have this
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesHuman, RMCEmotesHuman);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesMoth, RMCEmotesMoth);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesReptilian, RMCEmotesReptilian);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesSlime, RMCEmotesSlime);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesAvali, RMCEmotesAvali);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesVulpkanin, RMCEmotesVulpkanin);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesRodentia, RMCEmotesRodentia);
        // Harmony change start - We don't have these species but we do have Vox
        // Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesFeroxi, RMCEmotesFeroxi);
        // Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesSkrell, RMCEmotesSkrell);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesVox, RMCEmotesVox);
        // Harmony Change end
        // Start Box Change: Scurret, IPC, Thaven, Allulalo 
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesScurret, RMCEmotesScurret);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesIPC, RMCEmotesIPC);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesThaven, RMCEmotesThaven);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesAllulalo, RMCEmotesAllulalo);
        // End Box Change

        Control.Initialize(); // Harmony
    }
}
