using System.Numerics;
using Content.Client.Lobby.UI.Loadouts;
using Content.Client.UserInterface.Controls;
using Content.Shared.Clothing;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map; // Box Change: Used for getting sprite
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Floof.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LoadoutMetadataEditorDialog : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _entSys = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _protoMan = default!;

    public event Action<Loadout>? OnSave;

    private readonly ProtoId<LoadoutPrototype> _loadoutProto;
    private readonly ProtoId<LoadoutGroupPrototype> _groupProto;
    private Loadout _loadout;
    private readonly EntityUid? _entity;

    //private LoadoutContainer _previewContainer; // Box Change: Get rid of the scuffed LoadoutContainer preview

    public LoadoutMetadataEditorDialog(Loadout currentState, ProtoId<LoadoutPrototype> loadoutProto, ProtoId<LoadoutGroupPrototype> groupProto)
    {
        IoCManager.InjectDependencies(this);
        _entSys.TryGetEntitySystem<LoadoutSystem>(out var loadoutSystem); // I don't want to bother passing it through the constructor
        _protoMan.TryIndex(loadoutProto, out var loadoutProtoResolved);

        _loadoutProto = loadoutProto;
        _groupProto = groupProto;
        RobustXamlLoader.Load(this);

        // We maintain a copy of the original loadout to avoid polluting the character profile in the event the user decides not to save the loadout
        _loadout = new Loadout(currentState);

        // Start Box Change: Replace scuffed LoadoutContainer preview with a SpriteView
        // Preview container shows current loadout
        //_previewContainer = new(loadoutProto, true, FormattedMessage.FromMarkupPermissive("Preview"));
        //_previewContainer.Name = _loadout.NameOverride ?? (loadoutProtoResolved != null ? loadoutSystem?.GetName(loadoutProtoResolved) : "<error>");
        //LoadoutPreviewContainer.AddChild(_previewContainer);

        if (loadoutProtoResolved != null)
        {
            var ent = loadoutProtoResolved.DummyEntity ?? _entMan.System<LoadoutSystem>().GetFirstOrNull(loadoutProtoResolved);
            _entity = _entMan.SpawnEntity(ent, MapCoordinates.Nullspace);
            Sprite.SetEntity(_entity);
        }
        else
        {
            Sprite.SetEntity(null);
        }
        // End Box Change

        Load(_loadout);

        CancelButton.OnPressed += _ => Close();
        SaveButton.OnPressed += _ =>
        {
            Save();
            Close();
        };
    }

    public void Load(Loadout currentState)
    {
        CustomNameField.Text = currentState.NameOverride is { Length: >0 } nameOverride ? nameOverride : string.Empty;
        CustomDescField.Text = currentState.DescriptionOverride is { Length: >0 } descOverride ? descOverride : string.Empty;
    }

    public void Save(bool raiseEvent = true)
    {
        // Sanitize data: empty text fields means no override, disabled color tint means no color tint
        string? customName = CustomNameField.Text.Trim();
        string? customDesc = CustomDescField.Text.Trim();

        if (customName.Length == 0)
            customName = null;
        if (customDesc.Length == 0)
            customDesc = null;

        _loadout.NameOverride = customName;
        _loadout.DescriptionOverride = customDesc;

        if (raiseEvent)
            OnSave?.Invoke(_loadout);

        Load(_loadout); // Just to update the fields with sanitized values
    }
}
